### PR TITLE
Adding new Lead Category Dropdown component along with an Overlay Box…

### PR DESCRIPTION
**Pull request by mfunkie**
… component that works with React Bootstrap's Overlay to make overlaying semi-dropdowns easy.

Note to Reviewer:

There are some minor inline styles here that are used because of programmatic application (positionTop and positionLeft), but there are also a couple that just didn't warrant a class (like overriding margins and padding for ul content).  Let me know if this drives you absolutely mad and I can try and cut a new boomstrap release for what would equate to maybe 3 lines of code in less.

### CODE REVIEW

**Comment by seanboom** [comment]
:moneybag:

**Comment by igreulich** [comment]
### Note
At the time of the comment, I have not looked at the code.

You make reference to cutting a new Boomstrap release if someone doesn't like the inline styles. Are they things that should really be in Boomstrap anyway?

**Comment by mfunkie** [comment]
It's just stuff specific to the component, and all of our .less files live in Boomstrap.

**Comment by mcraiganthony** [comment]
I'll take a look in a bit.

**Comment by mcraiganthony** [comment]
Also, if we look at the React-Bootstrap project (http://react-bootstrap.github.io/components.html) we will see that the rendered components match the component markup and class names seen in Bootstrap.

**Comment by mcraiganthony** [comment]
Regarding the LeadCategoryByType component ... do you guys think it would be wise to include this in Boomstrap and also build out the dropdown version?

**Comment by mfunkie** [comment]
I'm not sure I understand what you mean by the LeadCategoryByType.  That already exists within this library, unless you mean to eject it.

**Comment by mfunkie** [comment]
I get what you're saying with matching the markup, but would appreciate line comments in specific areas.  If you mean usage of `dropdown-menu`, `dropdown-menu` was used to match the look and feel for an OverlayBox to match a dropdown menu.  If I need to make a new class for it, so be it, but the OverlayBox's root node needs to be something that is position:absolute, so simply nesting the ul with dropdown-menu in a div won't match/fit.

**Comment by mcraiganthony** [comment]
LeadCategoryByType only exists on the React side. To remain consistent with our pattern library, it should be built in Boomstrap first.

**Comment by mfunkie** [comment]
I'm just not sure why that's being discussed here. It's an orchestration of components, not part of this PR, and you approved it 10 days ago.

**Comment by mcraiganthony** [comment]
Sorry I wasn't more clear. I'm specifically referring to the dropdown button itself. Markup needs to follow this patter:

<div class="btn-group">
      <button type="button" class="btn btn-link dropdown-toggle">
        <span class="leadcat leadcat-nurture">nurture</span> <span class="caret"></span>
      </button>
</div>

Regarding the LeadCategoryByType ... you are right. I should have thought it through a little more before approving the PR. Now that I see it being used again in a dropdown, it dawned on me that it would be wise to get it in Boomstrap.

**Comment by mfunkie** [comment]
I started with a `<Button bsStyle='link' />` but it added some weird highlighting and underlining that I couldn't really get around without being hacky.

**Comment by mfunkie** [comment]
We probably need to have a larger discussion on what is 'Pattern Library' and what is 'Component Library'.  They've kinda mucked themselves together in Boomstrap so there's no clear separation there.  As far as I understand it, a Pattern Library would be a clear list of patterns, methodologies and the utmost base-level Components.  In our case here, categories are almost an extension of Markers (which I would consider to be the pattern).

For example: http://ux.mailchimp.com/patterns
You don't see much past the ground level of what composes a page, but I'm almost certain they've built more complex UIs from these patterns.

I'm not even sure how we would reconcile this, myself.

**Comment by mfunkie** [comment]
Closing due to design changes ultimately rendering half of this meaningless.

**Pull request closed without merging**
