### PR TITLE
Remove Ficon

### PR DESCRIPTION
**Pull request by igreulich**
This release **fully** replaces font-icons with svg-icons.

Basicaly @mcraiganthony cleaned up all the places that were using icons of any sort, (font icons directly or Icon component) and made them use the SvgIcon component...

...which I then killed.

By killed I mean turned into the Icon component.

So the **only** Icon component is now svg based.

**[EDIT]** not does not mean the same thing as now.

### CODE REVIEW

**Comment by seanboom** [comment]
> So the only Icon component is not svg based.

Can't figure out what you mean here.

**Comment by seanboom** [comment]
Oh, oh. I get it. the only = only the. I should have read that slower.

**Comment by igreulich** [comment]
@seanboom No, you were right the first time. But thanks for giving me the benefit of the doubt.

Also I fixed the glitch.

**Comment by mfunkie** [comment]
Looks great!  In your generated code, why does defineProperty look different? Do you have a different Babel version from the last person to generate? I haven't looked into upgrading Babel since the lodash incident.  Might be worth reinvestigating.

**Comment by igreulich** [comment]
I am running Babel 5.2.15, Which looks like an older version, based on the package.json.

**Pull request merged**
