### PR TITLE
Eslint and peerDependencies warnings.

### PR DESCRIPTION
**Pull request by AlexKVal**
There is already `.eslintignore` file exist, so just use it fo full blacklisting
instead of whitelisting in config parameters `eslint -c .eslintrc --ext .js --ext .jsx src/.`

And fix for npm warnings
```
The peer dependency babel-core@* included from babel-loader will no
The peer dependency node-libs-browser@>= 0.4.0 <=0.6.0 included from webpack will no
```

### CODE REVIEW

**Comment by mfunkie** [comment]
And will this pick up all of the jsx files without the extension set?

**Comment by AlexKVal** [comment]
Sorry.. forgot `www` generated folder.

> And will this pick up all of the jsx files without the extension set?

hmm.. my bad, didn't check it. No. It doesn't. I'll try to find out a solution.

**Comment by AlexKVal** [comment]
`.eslintrc`
```js
"extensions": [
   ".jsx", ".js"
 ],
```
It should work because of this patch: https://github.com/Holixus/eslint/commit/3be29956facae148eec43d24a7a29e7ce0ab110b
But it doesn't :cry:

**Comment by AlexKVal** [comment]
Let it be like this: `"lint": "eslint --ext .js --ext .jsx .",` for now :smile: 

It seems we found out bug in `eslint` (or absent feature).
I'll try to work with `eslint` on this.

**Comment by mfunkie** [comment]
Works for me, thanks for following up.

**Comment by AlexKVal** [comment]
As it turned out it is `absent feature` :smile: 
but to make a realization for it would be a bit hard.

`Eslint` at first constructs the list of files for linting,
then traverses one by one and
*here is the hard part*
it searches for `.eslintrc` every time for every file.

Therefore it would be task of `egg or chicken came first`.

--
In case you are interested here is [the eslint code](https://github.com/eslint/eslint/blob/d007063bddc3674cac6c09ace68fb692d36d3116/lib/cli-engine.js#L313-L323)
`extensions: options.extensions` <- this is not from `.eslintrc`. 
It's from [defaults](https://github.com/eslint/eslint/blob/d007063bddc3674cac6c09ace68fb692d36d3116/lib/cli-engine.js#L80)
And options from `.eslintrc` are read only inside of `processFile(filename, configHelper)` [here](https://github.com/eslint/eslint/blob/d007063bddc3674cac6c09ace68fb692d36d3116/lib/cli-engine.js#L183)
Therefore our coveted `extentions` option could be read only *after* traversing of files begins,
but we need it before.

--
Sorry for my missive :cherries:

**Pull request merged**
