### PR TITLE
Use React.PropTypes.node as type for children property.

### PR DESCRIPTION
**Pull request by AlexKVal**
And small aesthetical strokes.

--
from https://facebook.github.io/react/docs/reusable-components.html
> React.PropTypes.node
// Anything that can be rendered: numbers, strings, elements or an array
// containing these types.

and https://github.com/yannickcr/eslint-plugin-react/issues/7#issuecomment-106949101

### CODE REVIEW

**Comment by mfunkie** [comment]
While yes, this could be a node, the intended usage here is for it to be a string.  I think I need @mcraiganthony to weigh in here. Should we accept other things than a string?

**Comment by AlexKVal** [comment]
I got idea from your documentation :wink: 
http://boomtownroi.github.io/boomstrap-react/#/docs/Callout
```js
<Callout>
  <p>Just a default callout without a heading and two paragraphs.</p>
  <p>Just a default callout without a heading and two paragraphs.</p>
</Callout>
```

See ? Two `<p>` elements as children :cherries:

**Comment by mfunkie** [comment]
Yeah I actually misread before I typed here, `heading` is the field I was thinking of that would be a string, and so I confused the two.  It looks like `children` could be an array also in addition to being a `node`, so I'm not sure `node` would cover all scenarios.

**Comment by mfunkie** [comment]
I re-read the documentation and saw that node can be an array.  So ignore my comment about that.

**Pull request merged**
